// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emvzxnueofunlwpfaouc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtdnp4bnVlb2Z1bmx3cGZhb3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDgwNDQsImV4cCI6MjA2Mzc4NDA0NH0.7fzlR3mkoaCjNsEoJoEXYX1EgrwR_xwEIR0y2nCEZ5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);